# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shownews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('to_include', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrapingRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='newskeyword',
            name='rule_id',
            field=models.ManyToManyField(to='shownews.ScrapingRule'),
        ),
        migrations.AlterUniqueTogether(
            name='newskeyword',
            unique_together=set([('name', 'to_include')]),
        ),
    ]
