# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shownews', '0002_auto_20180119_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newskeyword',
            name='rule_id',
        ),
        migrations.AddField(
            model_name='scrapingrule',
            name='keywords',
            field=models.ManyToManyField(to='shownews.NewsKeyword'),
        ),
        migrations.AlterField(
            model_name='newskeyword',
            name='to_include',
            field=models.BooleanField(default=True),
        ),
    ]
