# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shownews', '0004_auto_20180121_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingrule',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
