# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shownews', '0006_auto_20180127_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdata',
            name='read_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsdata',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
