# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shownews', '0007_auto_20180128_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsdata',
            options={'ordering': ['-time', '-creation_time']},
        ),
    ]
