# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shownews', '0008_auto_20180128_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
            options={
                'ordering': ['-weight'],
            },
        ),
        migrations.AddField(
            model_name='newsdata',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='scoremap',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shownews.NewsData'),
        ),
        migrations.AddField(
            model_name='scoremap',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shownews.ScrapingRule'),
        ),
        migrations.AlterUniqueTogether(
            name='scoremap',
            unique_together=set([('news', 'rule')]),
        ),
    ]
