version: '2'

services:
  db:
    restart: always
    image: postgres:10.3-alpine
    container_name: db01
    environment:
      POSTGRES_USER: dja1
      POSTGRES_PASSWORD: _MY_DB_PASSWORD_
      POSTGRES_DB: my_focus_news

  nginx:
    restart: always
    image: nginx:1.13-alpine
    container_name: nginx01
    ports:
      - "8080:80"
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
    volumes_from:
      - web
    depends_on:
      - web
    links:
      - web:web

  web:
    restart: always
    build:
      context: ./my-python-env
      args:
        PROJECT_NAME: "my_focus_news"
    container_name: web01
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn my_focus_news.wsgi -b 0.0.0.0:8001"
    volumes:
      - ../../../my_focus_news:/src
      - /static
    expose:
      - "8001"
    depends_on:
      - db
    links:
      - db:db

  scraper:
    restart: always
    build:
      context: ./my-python-env
      args:
        PROJECT_NAME: "news_scraper"
    container_name: scraper01
    command: bash -c "sleep 30 && python schedule.py"
    volumes:
      - ../../../news_scraper:/src
    depends_on:
      - db
      - web
    links:
      - db:db
